inherit_from: '.rubocop_todo.yml'

AllCops:
  TargetRubyVersion: 2.7

Style/AsciiComments:
  Enabled: false

Metrics/BlockLength:
  Max: 150
  Exclude:
    - spec/**/*

Metrics/ModuleLength:
  Max: 160
